#!/bin/bash

# Basic Arithmetic
num1=3
num2=2
num3=$((num1+num2))
num4=$((num1**num2))
num5=$((num1%num2))

echo "3 + 2 = $num3"
echo "3^2 = $num4"
echo "3 % 2 = $num5"

# Shorthand incrementing
i=4
let i+=1
echo "4 += 1 -> $i"
echo "5++ -> $((i++))"
echo "++6 -> $((++i))"

# Floating point with Python
var1=1.2
var2=5.5
sum=$(python -c "print($var1+$var2)")
echo "1.2 + 5.5 = $sum"
